project:
  type: book
  output-dir: docs

book:
  title: "Quarto Book"
  author: "John Doe"
  chapters:
    - index.qmd
    - matters/preface.qmd
    - matters/introduction.qmd
    - chapters/world-is-flat.qmd
    - chapters/world-is-not-flat.qmd

format:
  html:
    theme:
      - cosmo
  epub:
    output-file: quarto-book.epub
