project:
  type: book
  output-dir: _book

book:
  title: "Quarto Book"
  author: "John Doe"
  output-file: quarto-book
  cover-image: assets/cover.png
  downloads:
    - epub
  chapters:
    - index.qmd
    - book/preface.qmd
    - book/introduction.qmd
    - book/chapters/world-is-flat.qmd
    - book/chapters/world-is-not-flat.qmd
  page-footer:
    left: "© 2026 Your Name"
    right:
      - icon: github
        href: https://github.com/cuimingda/quarto-book

format:
  html:
    theme:
      - cosmo
  epub: default
